language: en

pipeline:
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
     case_sensitive: False
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: KeywordIntentClassifier
     case_sensitive: False
#     constrain_similarities: true
#   - name: ar_numeric.ArabicNumeric
#   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 300
     retrieval_intent: faq
     constrain_similarities: true
   - name: FallbackClassifier
     threshold: 0.5
     ambiguity_threshold: 0.1

policies:
   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
     constrain_similarities: true
   - name: RulePolicy
     core_fallback_threshold: 0.4
     core_fallback_action_name: "action_default_fallback"
     enable_fallback_prediction: True
