institute = {
    "1": ["Australian National University (ANU)", "James Cook University",
          "Macquarie University",
          "Monash University",
          "RMIT University",
          "The University of Adelaide",
          "The University of Melbourne",
          "The University of New South Wales (UNSW)",
          "The University of Queensland (UQ)",
          "The University of Sydney",
          "The University of Western Australia (UWA)",
          "University of Newcastle",
          "University of Technology Sydney (UTS)"],
    "2": [
        "Technische Universität Wien",
        "Universität Innsbruck",
        "Universität Wien",
    ],
    "3": [
        "Katholieke Universiteit Leuven",
        "Université Catholique de Louvain (UCL)",
        "Université Libre de Bruxelles (ULB)",
        "University of Antwerp",
        "University of Ghent",
        "Vrije Universiteit Brussel (VUB)",
    ],
    "4": [
        "McGill University",
        "McMaster University",
        "University of Alberta",
        "University of British Columbia",
        "University of Calgary",
        "University of Toronto",
        "University of Waterloo",
    ],
    "5": [
        "Beihang University",
        "Central South University",
        "China Agricultural University",
        "China University of Geosciences",
        "Chongqing University",
        "Dalian University of Technology",
        "East China Normal University",
        "Fudan University",
        "Harbin Institute of Technology",
        "Huazhong University of Science and Technology",
        "Hunan University",
        "Jilin University",
        "Nanjing University",
        "Nankai University",
        "Northwestern Polytechnical University",
        "Peking University",
        "Shanghai Jiao Tong University",
        "Sichuan University",
        "Soochow University",
        "South China University of Technology",
        "Sun Yat-sen University",
        "Tianjin University",
        "Tongji University",
        "Tsinghua University",
        "University of Science and Technology of China",
        "Wuhan University",
        "Xiamen University",
        "Xi'an Jiaotong University",
        "Zhejiang University",
    ],
    "6": [
        "Aalborg University",
        "Aarhus University",
        "Technical University of Denmark",
        "University of Copenhagen",
        "University of Southern Denmark",
    ],
    "7": [
        "Aalto University",
        "University of Helsinki"
    ],
    "8": [
        "Ecole Normale Supérieure de Lyon",
        "Ecole Polytechnique",
        "Sorbonne University",
        "Université de Bordeaux",
        "Université de Montpellier",
        "Université Grenoble-Alpes (UGA)",
    ],
    "9": [
        "Christian-Albrechts-Universität zu Kiel",
        "Johannes Gutenberg Universität Mainz",
        "KIT, Karlsruher Institut für Technologie",
        "Rheinisch-Westfälische Technische Hochschule Aachen",
        "Ruhr-Universität Bochum",
        "Ruprecht-Karls-Universität Heidelberg",
        "Technische Universität Berlin",
        "Technische Universität Darmstadt",
        "Technische Universität Dresden",
        "Technische Universität München",
        "Universität Bayreuth",
        "Universität Bielefeld",
        "Universität Duisburg-Essen",
        "Universität Erlangen-Nürnberg",
        "Universität Freiburg",
        "Universität Hamburg",
        "Universität Köln",
        "Universität Konstanz",
        "Universität Stuttgart",
    ],
    "10": [
        "City University of Hong Kong",
        "The Chinese University of Hong Kong (CUHK)",
        "The Hong Kong Polytechnic University",
        "The Hong Kong University of Science and Technology (HKUST)",
        "University of Hong Kong (HKU)",
    ],
    "11": [
        "Trinity College Dublin (TCD)",
        "University College Dublin (UCD)"
    ],
    "12": [
        "Sapienza - Università di Roma",
        "Università degli Studi di Milano",
        "Università di Bologna (UNIBO)",
        "Università di Pisa",
        "Università Vita-Salute San Raffaele",
    ],
    "13": [
        "Hokkaido University"
        "Keio University"
        "Kyoto University"
        "Kyushu University"
        "Nagoya University"
        "Osaka University"
        "The University of Tokyo"
        "Tohoku University"
        "Tokyo Institute of Technology"
        "University of Tsukuba"
        "Waseda University"
    ],
    "14": [
        "Universiti Malaya (UM)"
    ],
    "15": [
        "Delft University of Technology",
        "Eindhoven University of Technology",
        "Erasmus University Rotterdam",
        "Leiden University",
        "Maastricht University",
        "Radboud University Nijmegen",
        "University of Amsterdam",
        "University of Groningen",
        "Utrecht University",
        "Vrije Universiteit Amsterdam",
        "Wageningen University",
    ],
    "16": [
        "The University of Auckland",
        "University of Otago",
    ],
    "17": [
        "University of Bergen",
        "University of Oslo",
        "Norwegian University of Science And Technology",
    ],
    "18": [
        "Nanyang Technological University (NTU)",
        "National University of Singapore (NUS)"
    ],
    "19": [
        "Hanyang University",
        "KAIST - Korea Advanced Institute of Science and Technology",
        "Korea University",
        "Kyung Hee University",
        "Pohang University of Science and Technology (POSTECH)",
        "Seoul National University (SNU)",
        "Sungkyunkwan University",
        "University of Ulsan",
        "Yonsei University",
    ],
    "20": [
        "Universidad Complutense de Madrid (UCM)",
        "Universitat Autónoma de Barcelona",
        "Universitat de Barcelona (UB)",
        "Universitat Pompeu Fabra",
    ],
    "21": [
        "Chalmers University of Technology",
        "KTH, Royal Institute of Technology",
        "Linköping University",
        "Lund University",
        "Stockholm University",
        "University of Gothenburg",
        "Uppsala University",
    ],
    "22": [
        "Ecole Polytechnique Fédérale de Lausanne (EPFL)"
        "University of Basel"
        "University of Bern"
        "University of Geneva"
        "University of Lausanne"
        "University of Zurich"
    ],
    "23": [
        "Cardiff University",
        "Durham University",
        "Imperial College London",
        "King's College London (KCL)",
        "London School of Economics and Political Science (LSE)",
        "Newcastle University",
        "Queen Mary University of London (QMUL)",
        "The University of Manchester",
        "The University of Nottingham",
        "The University of Sheffield",
        "The University of Warwick",
        "UCL (University College London)",
        "University of Birmingham",
        "University of Bristol",
        "University of Cambridge",
        "University of Dundee",
        "University of East Anglia (UEA)",
        "University of Exeter",
        "University of Leeds",
        "University of Leicester",
        "University of Liverpool",
        "University of Oxford",
        "University of Southampton",
        "University of St Andrews",
        "University of York",
    ],
    "24": [
        "Queen's University of Belfast"
    ],
    "25": [
        "University of Edinburgh",
        "University of Glasgow"
    ],
    "26": [
        "University of Leeds",
        "University of Leicester",
        "University of Liverpool"
        "University of Oxford",
        "University of Southampton",
        "University of St Andrews"
        "University of York",
        "Boston College"
        "Boston University",
        "Brandeis University",
        "Brown University",
        "California Institute of Technology (Caltech)",
        "Carnegie Mellon University",
        "Case Western Reserve University",
        "Columbia University",
        "Cornell University",
        "Dartmouth College",
        "Duke University",
        "Emory University",
        "George Washington University",
        "Georgetown University",
        "Georgia Institute of Technology (Georgia Tech)",
        "Harvard University",
        "Indiana University Bloomington",
        "Johns Hopkins University",
        "Massachusetts Institute of Technology (MIT)"
        "Michigan State University",
        "New York University (NYU)",
        "North Carolina State University",
        "Northeastern University",
        "Northwestern University",
        "Ohio State University",
        "Pennsylvania State University",
        "Princeton University",
        "Purdue University",
        "Rice University"
        "Rutgers - The State University of New Jersey, New Brunswick",
        "Rutgers - The State University of New Jersey, Newark",
        "Stanford University",
        "Stony Brook University",
        "Texas A&M University",
        "The University of Georgia",
        "Tufts University",
        "Tulane University",
        "University at Buffalo SUNY",
        "University of California, Berkeley (UCB)",
        "University of California, Davis (UCD)",
        "University of California, Irvine (UCI)",
        "University of California, Los Angeles (UCLA)",
        "University of California, Riverside (UCR)",
        "University of California, San Diego (UCSD)",
        "University of California, Santa Barbara (UCSB)",
        "University of California, Santa Cruz (UCSC)",
        "University of Chicago",
        "University of Colorado at Boulder",
        "University of Delaware",
        "University of Florida"
        "University of Illinois at Urbana-Champaign",
        "University of Illinois, Chicago (UIC)",
        "University of Iowa",
        "University of Maryland, College Park",
        "University of Massachusetts, Amherst"
        "University of Miami",
        "University of Michigan-Ann Arbor",
        "University of Minnesota Twin Cities",
        "University of North Carolina, Chapel Hill",
        "University of Notre Dame",
        "University of Pennsylvania",
        "University of Pittsburgh",
        "University of Rochester",
        "University of Southern California",
        "University of Tennessee",
        "University of Texas at Austin",
        "University of Virginia",
        "University of Washington",
        "University of Wisconsin-Madison",
        "Vanderbilt University",
        "Virginia Polytechnic Institute (Virginia Tech)",
        "Washington University in St. Louis",
        "Yale University",
    ]
}
